name: Deploy Moodle to Docker Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version
        
      - name: Configure Docker to connect to Docker Desktop
        run: |
          echo "DOCKER_HOST=tcp://host.docker.internal:2375" >> $GITHUB_ENV
          
      - name: Start Docker Desktop
        run: |
          docker info
          
      - name: Deploy to Docker Desktop
        run: |
          docker-compose up -d
          
      - name: Check containers
        run: |
          docker ps
          
      - name: Wait for services
        run: |
          sleep 30
          
      - name: Check Moodle service
        run: |
          curl http://localhost:80 || true
